import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import mongoose from 'mongoose'
import Link from 'next/link'
import bodyParser from 'body-parser'

export default function addTask () {
    return (
        <>
        <Head>
            <title>Tareas App - Made by Franco Piccirilli</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <h1 className="titlePage">Añadir Tarea</h1>
            <div className="containerBtn">
                <input type="text" placeholder="Título de la tarea" className="inputTitleTask" />
                <input type="text" placeholder="Título de la tarea" className="inputTitleTask" />
                <input type="text" placeholder="Título de la tarea" className="inputTitleTask" />
                <input type="date" placeholder="Título de la tarea" className="inputTitleTask" />
                <Link href="/api/addTask"><a>Registrar</a></Link>
            </div>
        </div>
        </>
    )
}