import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import mongoose from 'mongoose'
import Link from 'next/link'
import bodyParser from 'body-parser'

export default function addTask () {
    return (
        <>
        <Head>
            <title>Tareas App - Made by Franco Piccirilli</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <h1 className="titlePage">Añadir Tarea</h1>
            <form className="containerBtn" action="/api/addTask" method="POST">
                <input type="text" placeholder="Título de la tarea" name="inputTitleTask" />
                <input type="text" placeholder="Descripcion de la tarea" name="inputDescTask" />
                <input type="text" placeholder="Notas adicionales" name="inputNoteTask" />
                <input type="date" placeholder="Fecha de entrega" name="inputDateTask" />
                <input type="submit" value="Añadir Tarea" name="btnAddTask" />
            </form>
        </div>
        </>
    )
}