import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import mongoose from 'mongoose'
import Link from 'next/link'
import mongoConnect from '../library/mongoConnect'
import tareaSchema from '../config/tareasSchema'
import bodyParser from 'body-parser'
import dayjs from 'dayjs'

export default function Home({ tasks }) {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Tareas App - Made by Franco Piccirilli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="titlePage">Tareas App</h1>
        <h3 className="descPage muted">Maneja tus tareas y tiempos desde esta app</h3>
        <div className="containerBtn">
          <Link href="/addTask">
          <a className="btnAddTask btn">Agregar Tarea</a>
          </Link>
          <div className="divider"></div>
          <Link href="/delTask">
          <a className="btnDelTask btn">Eliminar Tarea</a>
          </Link>
        </div>
        <div className="containerFromTaskList">
          {
            tasks.map((task) => {
              return (
                <div className="taskList" key={task._id}>
                  <div className="taskListTitle">
                    <h3>{task.titulo}</h3>
                    <p>{task.descripcion}</p>
                    <p>{task.notaAdicional}</p>
                    <p>{
                    dayjs(task.fecha).format('DD/MM/YYYY')
                    }
                    </p>
                  </div>
                </div>
              )
            })
          }
        </div>
      </div>
    </div>
    </>
  )
}

export async function getServerSideProps () {
  const mongo = await mongoConnect();
  const tasks = await tareaSchema.find({});
  console.log(tasks)
  return {
    props: {
      tasks: JSON.parse(JSON.stringify(tasks)),
    }
  }
}
